// Static site content: nail-shape categories and UI translations (zh/en/fr).
// Product records themselves live in Supabase — see src/products-api.js.
export const CATEGORIES = [
  { key: 'almond', label: '杏仁形', labelEn: 'Almond', labelFr: 'Amande' },
  { key: 'coffin', label: '棺形', labelEn: 'Coffin', labelFr: 'Cercueil' },
  { key: 'duck', label: '鸭嘴形', labelEn: 'Duck-Shaped', labelFr: 'Bec de Canard' },
  { key: 'french-regular', label: '法式 · 常规长度', labelEn: 'French · Regular', labelFr: 'French · Longueur Standard' },
  { key: 'french-short', label: '法式 · 短款', labelEn: 'French · Short', labelFr: 'French · Court' },
  { key: 'nude', label: '裸色', labelEn: 'Nude', labelFr: 'Nude' },
  { key: 'plain', label: '纯色', labelEn: 'Plain', labelFr: 'Uni' },
  { key: 'short-squoval', label: '短方圆', labelEn: 'Short Squoval', labelFr: 'Squoval Court' },
];

export const UI_STRINGS = {
  promoBar: { zh: '全场满 {amt} 免运费 · 支持 PayPal / 信用卡付款', en: 'Free shipping over {amt} · PayPal / Card accepted', fr: 'Livraison gratuite dès {amt} · PayPal / Carte acceptés' },
  heroEyebrow: { zh: 'WINNIPEG, CANADA · 个人精选品牌', en: 'WINNIPEG, CANADA · INDEPENDENT BRAND', fr: 'WINNIPEG, CANADA · MARQUE INDÉPENDANTE' },
  trustItem1: { zh: '小批量甄选', en: 'Small-batch curated', fr: 'Sélection en petite quantité' },
  trustItem2: { zh: '亲自试戴挑选', en: 'Personally tried & chosen', fr: 'Essayé et choisi personnellement' },
  trustItem3: { zh: '加拿大发货', en: 'Ships from Canada', fr: 'Expédié du Canada' },
  trustItem4: { zh: '安全便捷支付', en: 'Secure checkout', fr: 'Paiement sécurisé' },
  navHome: { zh: '首页', en: 'Home', fr: 'Accueil' },
  navShop: { zh: '全部商品', en: 'Shop All', fr: 'Boutique' },
  navAbout: { zh: '关于我', en: 'About', fr: 'À propos' },
  navReviews: { zh: '评价', en: 'Reviews', fr: 'Avis' },
  navContact: { zh: '联系方式', en: 'Contact', fr: 'Contact' },
  navLogin: { zh: '登录', en: 'Log In', fr: 'Connexion' },
  navAccount: { zh: '我的账号', en: 'My Account', fr: 'Mon Compte' },
  cart: { zh: '购物车', en: 'Cart', fr: 'Panier' },
  heroTitle1: { zh: '手工甲片', en: 'Handmade Nails', fr: 'Ongles Artisanaux' },
  heroTitle2: { zh: '个人精选进货', en: 'Personally Curated', fr: 'Sélection Personnelle' },
  heroSubtitle: { zh: '每一款都是我亲自挑选、小批量进货的穿戴甲，选好尺码，直接下单。', en: 'Every design is hand-picked and stocked in small batches by me — pick your size and order directly.', fr: 'Chaque modèle est choisi et stocké en petite quantité par mes soins — choisissez votre taille et commandez.' },
  heroButton: { zh: '选购全部商品', en: 'Shop All', fr: 'Voir la Boutique' },
  featuredLabel: { zh: '本周精选', en: 'This Week', fr: 'Cette Semaine' },
  featuredTitle: { zh: '编辑之选', en: "Editor's Picks", fr: 'Sélection de la Rédaction' },
  viewAll: { zh: '查看全部商品 →', en: 'View all products →', fr: 'Voir tous les produits →' },
  categoryLabel: { zh: '款式分类', en: 'Shop by Shape', fr: 'Par Forme' },
  categoryTitle: { zh: '按甲型挑选', en: 'Browse by Nail Shape', fr: 'Parcourir par Forme' },
  unitCount: { zh: '款', en: ' styles', fr: ' styles' },
  reviewsLabel: { zh: '客户都在说', en: 'What Customers Say', fr: 'Avis Clients' },
  reviewsTitle: { zh: '真实反馈', en: 'Real Feedback', fr: 'Retours Authentiques' },
  viewAllReviews: { zh: '查看全部评价 →', en: 'View all reviews →', fr: 'Voir tous les avis →' },
  shopTitle: { zh: '全部商品', en: 'All Products', fr: 'Tous les Produits' },
  filterAll: { zh: '全部', en: 'All', fr: 'Tous' },
  breadcrumbHome: { zh: '首页', en: 'Home', fr: 'Accueil' },
  selectSize: { zh: '选择尺码', en: 'Select Size', fr: 'Choisir la Taille' },
  addToCart: { zh: '加入购物车', en: 'Add to Cart', fr: 'Ajouter au Panier' },
  addedToast: { zh: '已加入购物车', en: 'Added to cart', fr: 'Ajouté au panier' },
  careLabel: { zh: '佩戴与养护', en: 'Wear & Care', fr: 'Port et Entretien' },
  careText: { zh: '佩戴前请用指甲抛光条打磨甲面，配合甲胶或双面胶固定，可反复粘贴佩戴 7–10 天。摘除时请用温水浸泡后轻轻取下，避免硬撬伤甲。', en: 'Buff the nail surface before applying with nail glue or adhesive tabs; wear for 7–10 days and reapply as needed. Soak in warm water before gently removing to avoid damage.', fr: 'Polissez la surface de l\'ongle avant application avec de la colle ou des languettes adhésives ; portez 7 à 10 jours. Trempez dans l\'eau tiède avant de retirer délicatement.' },
  sameCategoryTitle: { zh: '同款式其他色号', en: 'More in this Shape', fr: 'Autres Coloris de cette Forme' },
  cartTitle: { zh: '购物车', en: 'Cart', fr: 'Panier' },
  subtotal: { zh: '小计', en: 'Subtotal', fr: 'Sous-total' },
  shippingNote: { zh: '运费和税费将在结算页计算', en: 'Shipping and tax calculated at checkout', fr: 'Frais de livraison et taxes calculés au paiement' },
  goCheckout: { zh: '去结算', en: 'Checkout', fr: 'Payer' },
  emptyCart: { zh: '购物车还是空的', en: 'Your cart is empty', fr: 'Votre panier est vide' },
  goShopBtn: { zh: '去逛逛', en: 'Start Shopping', fr: 'Découvrir la Boutique' },
  checkoutTitle: { zh: '结算', en: 'Checkout', fr: 'Paiement' },
  shippingInfoLabel: { zh: '收货信息', en: 'Shipping Info', fr: 'Informations de Livraison' },
  fieldName: { zh: '姓名', en: 'Full name', fr: 'Nom complet' },
  fieldEmail: { zh: '邮箱', en: 'Email', fr: 'E-mail' },
  fieldAddress: { zh: '收货地址', en: 'Address', fr: 'Adresse' },
  fieldCity: { zh: '城市', en: 'City', fr: 'Ville' },
  fieldZip: { zh: '邮编', en: 'ZIP Code', fr: 'Code Postal' },
  fieldCountry: { zh: '国家/地区', en: 'Country / Region', fr: 'Pays / Région' },
  paymentLabel: { zh: '付款方式', en: 'Payment Method', fr: 'Mode de Paiement' },
  paypalHint: { zh: '通过 PayPal 安全支付，支持 PayPal 余额或信用卡/借记卡访客付款，卡号不会经过本站。', en: 'Pay securely via PayPal — supports PayPal balance or guest checkout with credit/debit card. Your card number never touches this site.', fr: 'Paiement sécurisé via PayPal — solde PayPal ou carte bancaire en tant qu’invité. Votre numéro de carte ne transite jamais par ce site.' },
  shippingRequiredAlert: { zh: '请先填写完整的收货信息再付款。', en: 'Please fill in all shipping info before paying.', fr: "Veuillez renseigner l'adresse de livraison avant de payer." },
  paymentError: { zh: '支付出现问题，请稍后重试。', en: 'Something went wrong with payment — please try again.', fr: "Un problème est survenu avec le paiement — veuillez réessayer." },
  paypalNotConfigured: { zh: '支付功能尚未配置，暂时无法下单。', en: 'Payment is not configured yet — checkout is unavailable.', fr: "Le paiement n'est pas encore configuré — la commande est indisponible." },
  orderSummary: { zh: '订单摘要', en: 'Order Summary', fr: 'Résumé de la Commande' },
  shippingLabelWord: { zh: '运费', en: 'Shipping', fr: 'Livraison' },
  totalLabel: { zh: '总计', en: 'Total', fr: 'Total' },
  placeOrder: { zh: '确认下单', en: 'Place Order', fr: 'Confirmer la Commande' },
  orderPlacedTitle: { zh: '订单已提交', en: 'Order Placed', fr: 'Commande Confirmée' },
  orderPlacedText: { zh: '感谢您的订购，我们会尽快为您安排发货。', en: 'Thank you for your order — we will get it ready to ship shortly.', fr: 'Merci pour votre commande — nous la préparons pour expédition sous peu.' },
  orderRefLabel: { zh: '订单编号', en: 'Order reference', fr: 'Référence de commande' },
  continueShopping: { zh: '继续购物', en: 'Continue Shopping', fr: 'Continuer les Achats' },
  aboutLabel: { zh: '关于我', en: 'About Me', fr: 'À propos de moi' },
  aboutTitle: { zh: '我的故事', en: 'My Story', fr: 'Mon Histoire' },
  aboutText1: { zh: 'BeautyChoice by MM 是由两位女性在加拿大温尼伯创立的酷儿品牌。灵感源自我们对美好事物的热爱——并由我们的拉布拉多犬 MM（有着出乎意料的好品味）引领——BeautyChoice 相信美是一种选择：灵活、愉悦、私人化。我们制作高品质的穿戴甲，易穿戴、易更换、令人喜爱。为那些想拥有美丽指尖、又不想被传统美甲店的时间、花费与限制所束缚的人设计。', en: 'BeautyChoice by MM is a queer-founded brand created by two women in Winnipeg, Canada. Inspired by a love for beautiful things—and guided by MM, our Labrador with surprisingly good taste—BeautyChoice celebrates beauty as choice: flexible, joyful, and personal. We create high-quality press-on nails that are easy to wear, easy to change, and easy to love. Designed for people who want beautiful fingertips without the time, cost, or limits of traditional salon nails.', fr: "BeautyChoice by MM est une marque queer fondée par deux femmes à Winnipeg, au Canada. Inspirées par notre amour des belles choses — et guidées par MM, notre labrador au goût étonnamment sûr — BeautyChoice célèbre la beauté comme un choix : flexible, joyeux et personnel. Nous créons des faux ongles de haute qualité, faciles à porter, à changer et à aimer. Conçus pour les personnes qui veulent de belles mains sans le temps, le coût ni les contraintes d'un salon traditionnel." },
  aboutText2: { zh: '两个女生，一只狗。每天都在做出美丽的选择。', en: 'Two women. One dog. Making beautiful choices, every day.', fr: 'Deux femmes. Un chien. Faire de beaux choix, chaque jour.' },
  aboutNote: { zh: 'Winnipeg, Canada', en: 'Winnipeg, Canada', fr: 'Winnipeg, Canada' },
  contactTitle: { zh: '联系方式', en: 'Contact', fr: 'Contact' },
  directContact: { zh: '直接联系', en: 'Get in Touch', fr: 'Nous Contacter' },
  emailValue: { zh: '邮箱：beautychoicebymm@gmail.com', en: 'Email: beautychoicebymm@gmail.com', fr: 'E-mail : beautychoicebymm@gmail.com' },
  replyTime: { zh: '回复时间：工作日 24 小时内', en: 'Reply time: within 24 hours on weekdays', fr: 'Délai de réponse : sous 24h en semaine' },
  socialLabel: { zh: '社交主页', en: 'Social', fr: 'Réseaux Sociaux' },
  messageLabel: { zh: '留言', en: 'Send a Message', fr: 'Envoyer un Message' },
  fieldQuestion: { zh: '想问的问题', en: 'Your question', fr: 'Votre question' },
  sendMessage: { zh: '发送留言', en: 'Send Message', fr: 'Envoyer' },
  messageSent: { zh: '留言已发送，我们会尽快回复你。', en: 'Message sent — we’ll get back to you soon.', fr: 'Message envoyé — nous vous répondrons bientôt.' },
  messageFailed: { zh: '发送失败，请稍后重试或直接发邮件给我们。', en: 'Failed to send — please try again or email us directly.', fr: "Échec de l'envoi — réessayez ou écrivez-nous directement." },
  reviewsPlaceholder: { zh: '（此页为占位结构，请替换为真实客户评价与晒单照片）', en: '(Placeholder layout — replace with real customer reviews and photos)', fr: '(Mise en page provisoire — remplacez par de vrais avis clients et photos)' },
  footerTagline: { zh: '手工甲片精选 · 个人进货品牌', en: 'Handmade nail sets · An independent brand', fr: 'Ongles artisanaux · Une marque indépendante' },
  footerTagline2: { zh: '每一款都亲自试戴挑选。', en: 'Every design personally tried and chosen.', fr: 'Chaque modèle est essayé et choisi personnellement.' },
  footerNav: { zh: '导航', en: 'Navigate', fr: 'Navigation' },
  footerPayment: { zh: '支持的付款方式', en: 'Payment Methods', fr: 'Moyens de Paiement' },
  footerPaymentValue: { zh: 'PayPal · 信用卡 / 借记卡', en: 'PayPal · Credit / Debit Card', fr: 'PayPal · Carte Bancaire' },
  footerCopyright: { zh: '© 2026 beautychoice. 个人品牌，非公司实体。', en: '© 2026 beautychoice. An independent brand, not a corporate entity.', fr: '© 2026 beautychoice. Marque indépendante, non une entité corporative.' },
  freeShip: { zh: '免运费', en: 'Free', fr: 'Gratuit' },
  noImage: { zh: '暂无图片', en: 'No image yet', fr: 'Aucune image' },
  loading: { zh: '加载中…', en: 'Loading…', fr: 'Chargement…' },
  loadError: { zh: '商品加载失败，请刷新重试。', en: 'Failed to load products — please refresh.', fr: 'Échec du chargement — veuillez rafraîchir.' },

  // ---- account / login ----
  loginTitle: { zh: '登录 / 注册', en: 'Log In / Sign Up', fr: 'Connexion / Inscription' },
  loginSubtitle: { zh: '首次使用邮箱登录会自动为你创建账号。', en: "First time signing in with an email creates your account automatically.", fr: "La première connexion avec un e-mail crée automatiquement votre compte." },
  loginWithGoogle: { zh: '使用 Google 继续', en: 'Continue with Google', fr: 'Continuer avec Google' },
  loginOr: { zh: '或', en: 'or', fr: 'ou' },
  loginEmailPlaceholder: { zh: '邮箱地址', en: 'Email address', fr: 'Adresse e-mail' },
  loginSendCode: { zh: '发送验证码', en: 'Send code', fr: 'Envoyer le code' },
  loginCodeSentHint: { zh: '验证码已发送至 {email}，请查收（包括垃圾邮件夹）。', en: 'A code was sent to {email} — check your inbox (and spam folder).', fr: 'Un code a été envoyé à {email} — vérifiez votre boîte de réception (et les spams).' },
  loginCodePlaceholder: { zh: '6 位验证码', en: '6-digit code', fr: 'Code à 6 chiffres' },
  loginVerify: { zh: '验证并登录', en: 'Verify & Log In', fr: 'Vérifier et se connecter' },
  loginResend: { zh: '重新发送', en: 'Resend code', fr: 'Renvoyer le code' },
  loginChangeEmail: { zh: '换一个邮箱', en: 'Use a different email', fr: 'Utiliser un autre e-mail' },
  loginMarketingOptIn: { zh: '订阅邮件，获取新品与优惠信息', en: 'Email me with news and offers', fr: "M'envoyer des nouveautés et offres par e-mail" },
  loginAgreeText: { zh: '继续即代表你同意我们的{tos}和{privacy}。', en: 'By continuing, you agree to our {tos} and {privacy}.', fr: 'En continuant, vous acceptez nos {tos} et notre {privacy}.' },
  termsOfServiceLabel: { zh: '服务条款', en: 'Terms of Service', fr: 'Conditions de Service' },
  privacyPolicyLabel: { zh: '隐私政策', en: 'Privacy Policy', fr: 'Politique de Confidentialité' },
  loginNotConfigured: { zh: '登录功能尚未配置。', en: 'Sign-in is not configured yet.', fr: "La connexion n'est pas encore configurée." },
  loginGenericError: { zh: '出了点问题，请稍后重试。', en: 'Something went wrong — please try again.', fr: 'Une erreur est survenue — veuillez réessayer.' },
  accountEmailLabel: { zh: '登录邮箱', en: 'Signed in as', fr: 'Connecté en tant que' },
  logoutLabel: { zh: '退出登录', en: 'Log Out', fr: 'Se Déconnecter' },
  myOrdersTitle: { zh: '我的订单', en: 'My Orders', fr: 'Mes Commandes' },
  noOrdersYet: { zh: '还没有订单，去逛逛吧。', en: "No orders yet — let's find something you'll love.", fr: "Aucune commande pour l'instant — allez faire un tour dans la boutique." },
  orderStatusPending: { zh: '处理中', en: 'Processing', fr: 'En traitement' },
  orderStatusShipped: { zh: '已发货', en: 'Shipped', fr: 'Expédiée' },
  trackingNumberLabel: { zh: '物流单号：', en: 'Tracking number: ', fr: 'Numéro de suivi : ' },
};
